{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fm-inference-sagemaker.fullname" . }}
  labels:
    {{- include "fm-inference-sagemaker.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "fm-inference-sagemaker.fullname" . }}
  labels:
    {{- include "fm-inference-sagemaker.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  hostPath:
    path: {{ .Values.persistence.hostPath }}
{{- end }}
