
release_version: v1.0.0

predictionContainer:
  imageUrl: ""
  pullPolicy: IfNotPresent
  replicaCount: 1

tileServiceContainer:
  imageUrl: ""
  pullPolicy: IfNotPresent
  replicaCount: 1

floodsContainer:
  imageUrl: ""
  pullPolicy: IfNotPresent
  replicaCount: 1

burnScarContainer:
  imageUrl: ""
  pullPolicy: IfNotPresent
  replicaCount: 1

cropContainer:
  imageUrl: ""
  pullPolicy: IfNotPresent
  replicaCount: 1

suryaRolloutContainer:
  imageUrl: ""
  pullPolicy: IfNotPresent
  replicaCount: 1

imagePullSecrets: ecr-registry-key

hostServices: ""

ingressPrediction:
  path: /api/predict
  tlsSecretName: ingress-tls

ingressSunTiler:
  path: /api/tiles
  tlsSecretName: ingress-tls
