
release_version: v1.0.0

predictionContainer:
  imageUrl: ""
  pullPolicy: IfNotPresent
  replicaCount: 1
  resources_request_cpu: "2"
  resources_request_memory: "8Gi"
  resources_limit_cpu: "3"
  resources_limit_memory: "12Gi"

tileServiceContainer:
  imageUrl: ""
  pullPolicy: IfNotPresent
  replicaCount: 1

floodsContainer:
  imageUrl: ""
  pullPolicy: IfNotPresent
  replicaCount: 1

burnScarContainer:
  imageUrl: ""
  pullPolicy: IfNotPresent
  replicaCount: 1

cropContainer:
  imageUrl: ""
  pullPolicy: IfNotPresent
  replicaCount: 1

suryaRolloutContainer:
  imageUrl: ""
  pullPolicy: IfNotPresent
  replicaCount: 1


goServicesContainer:
  imageUrl: "ghcr.io/amarouane-abdelhak/temporalio-fib-worker:1.x.2"
  replicaCount: 5
  resources_request_cpu: "500m"
  resources_request_memory: "512Mi"
  resources_limit_cpu: "2000m"
  resources_limit_memory: "1Gi"



imagePullSecrets: ecr-registry-key

hostServices: ""

ingressPrediction:
  path: /api/predict
  tlsSecretName: ingress-tls

ingressSunTiler:
  path: /api/tiles
  tlsSecretName: ingress-tls

ingressV2Services:
  path: /api/predict/v2
