"""inference status

Revision ID: 06eee2001d6c
Revises: 05bdea251790
Create Date: 2026-01-23 04:07:57.686310

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "06eee2001d6c"
down_revision = "05bdea251790"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the PostgreSQL enum type before using it in a column
    inference_status_enum = sa.Enum(
        "queued",
        "download",
        "pre_inference",
        "inference",
        "post_inference",
        "complete",
        "failed",
        name="inferencestatus",
    )
    inference_status_enum.create(op.get_bind(), checkfirst=True)

    # Add new columns as nullable first so existing rows don't violate constraints
    op.add_column(
        "inferences", sa.Column("status", inference_status_enum, nullable=True)
    )
    op.add_column("inferences", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("inferences", sa.Column("error_stage", sa.String(), nullable=True))
    op.add_column("inferences", sa.Column("error_message", sa.String(), nullable=True))

    # Backfill new columns for existing rows, then enforce NOT NULL where required
    op.execute("UPDATE inferences SET status='queued' WHERE status IS NULL")
    op.execute("UPDATE inferences SET updated_at=created_at WHERE updated_at IS NULL")
    op.alter_column("inferences", "status", nullable=False)
    op.alter_column("inferences", "updated_at", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inferences", "error_message")
    op.drop_column("inferences", "error_stage")
    op.drop_column("inferences", "updated_at")
    op.drop_column("inferences", "status")

    # Drop enum type if it exists
    inference_status_enum = sa.Enum(
        "queued",
        "init",
        "download",
        "inference",
        "db_update",
        "complete",
        "failed",
        name="inferencestatus",
    )
    inference_status_enum.drop(op.get_bind(), checkfirst=True)
