"""Descriptive message for the migration

Revision ID: 5de2554bb5f2
Revises: 
Create Date: 2025-08-28 01:20:58.565909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de2554bb5f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_type', sa.Enum('huggingface', 's3', 'local', name='datasetsourcetype'), nullable=False),
    sa.Column('source_details', sa.JSON(), nullable=False),
    sa.Column('repo_id', sa.String(), nullable=True),
    sa.Column('bucket', sa.String(), nullable=True),
    sa.Column('prefix', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('validating', 'pending', 'copying', 'ready', 'failed', name='datasetstatus'), nullable=False),
    sa.Column('s3_path', sa.String(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('num_classes', sa.Integer(), nullable=False),
    sa.Column('backbone', sa.String(), nullable=False),
    sa.Column('num_epochs', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('classification', 'segmentation', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'deleted', name='jobstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('sagemaker_job_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('num_workers', sa.Integer(), nullable=True),
    sa.Column('data_path', sa.String(), nullable=True),
    sa.Column('usecase', sa.String(), nullable=True),
    sa.Column('means', sa.JSON(), nullable=True),
    sa.Column('stds', sa.JSON(), nullable=True),
    sa.Column('num_frames', sa.Integer(), nullable=True),
    sa.Column('output_bands', sa.Integer(), nullable=True),
    sa.Column('indices', sa.JSON(), nullable=True),
    sa.Column('dataset_bands', sa.JSON(), nullable=True),
    sa.Column('loss_function', sa.String(), nullable=True),
    sa.Column('img_grep', sa.String(), nullable=True),
    sa.Column('label_grep', sa.String(), nullable=True),
    sa.Column('train_split_path', sa.String(), nullable=True),
    sa.Column('val_split_path', sa.String(), nullable=True),
    sa.Column('test_split_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.String(), nullable=False),
    sa.Column('artifact_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artifacts')
    op.drop_table('jobs')
    op.drop_table('datasets')
    # ### end Alembic commands ###
