"""Add user details to inference.

Revision ID: 9a8fdc2b49e8
Revises: bcca3e997123
Create Date: 2025-09-15 10:43:42.447774

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "9a8fdc2b49e8"
down_revision = "bcca3e997123"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inferences", sa.Column("user_email", sa.String(length=254), nullable=False)
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inferences", "user_email")
