"""Add user details to inference.

Revision ID: 9a8fdc2b49e8
Revises: bcca3e997123
Create Date: 2025-09-15 10:43:42.447774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a8fdc2b49e8'
down_revision = 'bcca3e997123'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datasets')
    op.drop_table('artifacts')
    op.drop_table('jobs')
    op.add_column('inferences', sa.Column('user_email', sa.String(length=254), nullable=False))
    op.alter_column('inferences', 'query',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inferences', 'query',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('inferences', 'user_email')
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('batch_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_classes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('backbone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('num_epochs', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_type', postgresql.ENUM('classification', 'segmentation', name='tasktype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'running', 'completed', 'failed', 'deleted', name='jobstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sagemaker_job_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('failed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('num_workers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('usecase', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('means', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('stds', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('num_frames', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('output_bands', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('indices', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('dataset_bands', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('loss_function', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('img_grep', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('label_grep', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('train_split_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('val_split_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('test_split_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name='jobs_dataset_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='jobs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('artifact_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('artifact_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('artifacts_job_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('artifacts_pkey'))
    )
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_type', postgresql.ENUM('huggingface', 's3', 'local', name='datasetsourcetype'), autoincrement=False, nullable=False),
    sa.Column('source_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('repo_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bucket', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prefix', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('validating', 'pending', 'copying', 'ready', 'failed', name='datasetstatus'), autoincrement=False, nullable=False),
    sa.Column('s3_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stats', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('datasets_pkey'))
    )
    # ### end Alembic commands ###
