"""Create related models

Revision ID: de28ddce0e07
Revises: None
Create Date: 2025-08-28 05:38:30.491716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de28ddce0e07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finetuned_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_type', sa.Enum('huggingface', 's3', name='sourcetype'), nullable=False),
    sa.Column('source_details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('data_config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('query', sa.JSON(), nullable=True),
    sa.Column('result_s3_path', sa.String(), nullable=True),
    sa.Column('result_geojson', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inference_finetuned_model',
    sa.Column('inference_id', sa.UUID(), nullable=False),
    sa.Column('finetuned_model_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['finetuned_model_id'], ['finetuned_models.id'], ),
    sa.ForeignKeyConstraint(['inference_id'], ['inferences.id'], ),
    sa.PrimaryKeyConstraint('inference_id', 'finetuned_model_id')
    )
    op.create_table('preloaded_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('event_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('inference_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['inference_id'], ['inferences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preloaded_events')
    op.drop_table('inference_finetuned_model')
    op.drop_table('inferences')
    op.drop_table('finetuned_models')
    # ### end Alembic commands ###
