
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-app
  labels:
    app: prediction-app
spec:
  replicas: {{ .Values.predictionContainer.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: prediction-app
  template:
    metadata:
      labels:
        app: prediction-app
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      containers:
        - name: prediction-container
          image: {{ .Values.predictionContainer.imageUrl }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: cache-volume
              mountPath: /root/.cache
          env:
          - name: RELEASE_VERSION
            value: {{ .Values.release_version  }}
          envFrom:
            - configMapRef:
                name: prediction-app-envs
            - configMapRef:
                name: oidc-envs
          resources:
            requests:
              cpu: {{ .Values.predictionContainer.resources_request_cpu }}
              memory: {{ .Values.predictionContainer.resources_request_memory  }}
            limits:
              #cpu: {{ .Values.predictionContainer.resources_limit_cpu }}
              memory: {{ .Values.predictionContainer.resources_limit_memory }}

      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: service-cache-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tile-service
  labels:
    app: tile-service
spec:
  replicas: {{ .Values.tileServiceContainer.replicaCount  }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: tile-service
  template:
    metadata:
      labels:
        app: tile-service
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      containers:
        - name: tile-service-container
          image: {{ .Values.tileServiceContainer.imageUrl }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: cache-volume
              mountPath: /root/.cache
          env:
          - name: RELEASE_VERSION
            value: {{ .Values.release_version  }}
          envFrom:
            - configMapRef:
                name: oidc-envs
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: service-cache-pvc
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-services-app
  labels:
    app: go-services-app
spec:
  replicas: {{ .Values.goServicesContainer.replicaCount }}
  revisionHistoryLimit: 8
  selector:
    matchLabels:
      app: go-services-app
  template:
    metadata:
      labels:
        app: go-services-app
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      containers:
        - name: go-services-container
          image: {{ .Values.goServicesContainer.imageUrl }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
          - name: GOMEMLIMIT
            value: "900MiB"   # ~90% of 1Gi
          envFrom:
            - configMapRef:
                name: prediction-app-envs
            - configMapRef:
                name: oidc-envs
          resources:
            requests:
              cpu: {{ .Values.goServicesContainer.resources_request_cpu }}
              memory: {{ .Values.goServicesContainer.resources_request_memory  }}
            limits:
              cpu: {{ .Values.goServicesContainer.resources_limit_cpu }}
              memory: {{ .Values.goServicesContainer.resources_limit_memory }}
