
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-app
  labels:
    app: prediction-app
spec:
  replicas: {{ .Values.predictionContainer.replicaCount  }}
  selector:
    matchLabels:
      app: prediction-app
  template:
    metadata:
      labels:
        app: prediction-app
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      containers:
        - name: prediction-container
          image: {{ .Values.predictionContainer.imageUrl }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: cache-volume
              mountPath: /root/.cache
          envFrom:
            - configMapRef:
                name: prediction-app-envs
            - configMapRef:
                name: oidc-envs
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: service-cache-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: floods-app
  labels:
    app: floods-app
spec:
  replicas: {{ .Values.floodsContainer.replicaCount  }}
  selector:
    matchLabels:
      app: floods-app
  template:
    metadata:
      labels:
        app: floods-app
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      runtimeClassName: nvidia
      containers:
        - name: pipeline-floods-container
          image: {{ .Values.floodsContainer.imageUrl }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: cache-volume
              mountPath: /root/.cache
          envFrom:
            - configMapRef:
                name: floods-app-envs
            - configMapRef:
                name: oidc-envs
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: service-cache-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: burn-scars-app
  labels:
    app: burn-scars-app
spec:
  replicas: {{ .Values.burnScarContainer.replicaCount  }}
  selector:
    matchLabels:
      app: burn-scars-app
  template:
    metadata:
      labels:
        app: burn-scars-app
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      runtimeClassName: nvidia
      containers:
        - name: pipeline-burn-scars-container
          image: {{ .Values.burnScarContainer.imageUrl }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: cache-volume
              mountPath: /root/.cache
          envFrom:
            - configMapRef:
                name: burn-scars-app-envs
            - configMapRef:
                name: oidc-envs
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: service-cache-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crop-classification-app
  labels:
    app: crop-classification-app
spec:
  replicas: {{ .Values.cropContainer.replicaCount  }}
  selector:
    matchLabels:
      app: crop-classification-app
  template:
    metadata:
      labels:
        app: crop-classification-app
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      runtimeClassName: nvidia
      containers:
        - name: pipeline-crop-classification-container
          image: {{ .Values.cropContainer.imageUrl }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: cache-volume
              mountPath: /root/.cache
          envFrom:
            - configMapRef:
                name: crop-classification-app-envs
            - configMapRef:
                name: oidc-envs
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: service-cache-pvc

