//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var Datasetsourcetype = &struct {
	Huggingface postgres.StringExpression
	S3          postgres.StringExpression
	Local       postgres.StringExpression
}{
	Huggingface: postgres.NewEnumValue("huggingface"),
	S3:          postgres.NewEnumValue("s3"),
	Local:       postgres.NewEnumValue("local"),
}
