//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var Datasetstatus = &struct {
	Validating postgres.StringExpression
	Pending    postgres.StringExpression
	Copying    postgres.StringExpression
	Ready      postgres.StringExpression
	Failed     postgres.StringExpression
}{
	Validating: postgres.NewEnumValue("validating"),
	Pending:    postgres.NewEnumValue("pending"),
	Copying:    postgres.NewEnumValue("copying"),
	Ready:      postgres.NewEnumValue("ready"),
	Failed:     postgres.NewEnumValue("failed"),
}
