//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var Inferencestatus = &struct {
	Queued        postgres.StringExpression
	Download      postgres.StringExpression
	PreInference  postgres.StringExpression
	Inference     postgres.StringExpression
	PostInference postgres.StringExpression
	Complete      postgres.StringExpression
	Failed        postgres.StringExpression
}{
	Queued:        postgres.NewEnumValue("queued"),
	Download:      postgres.NewEnumValue("download"),
	PreInference:  postgres.NewEnumValue("pre_inference"),
	Inference:     postgres.NewEnumValue("inference"),
	PostInference: postgres.NewEnumValue("post_inference"),
	Complete:      postgres.NewEnumValue("complete"),
	Failed:        postgres.NewEnumValue("failed"),
}
