//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var Tasktype = &struct {
	Classification postgres.StringExpression
	Segmentation   postgres.StringExpression
}{
	Classification: postgres.NewEnumValue("classification"),
	Segmentation:   postgres.NewEnumValue("segmentation"),
}
