//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type Basefm string

const (
	Basefm_Surya   Basefm = "surya"
	Basefm_Prithvi Basefm = "prithvi"
)

var BasefmAllValues = []Basefm{
	Basefm_Surya,
	Basefm_Prithvi,
}

func (e *Basefm) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "surya":
		*e = Basefm_Surya
	case "prithvi":
		*e = Basefm_Prithvi
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for Basefm enum")
	}

	return nil
}

func (e Basefm) String() string {
	return string(e)
}
