//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type Datasetsourcetype string

const (
	Datasetsourcetype_Huggingface Datasetsourcetype = "huggingface"
	Datasetsourcetype_S3          Datasetsourcetype = "s3"
	Datasetsourcetype_Local       Datasetsourcetype = "local"
)

var DatasetsourcetypeAllValues = []Datasetsourcetype{
	Datasetsourcetype_Huggingface,
	Datasetsourcetype_S3,
	Datasetsourcetype_Local,
}

func (e *Datasetsourcetype) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "huggingface":
		*e = Datasetsourcetype_Huggingface
	case "s3":
		*e = Datasetsourcetype_S3
	case "local":
		*e = Datasetsourcetype_Local
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for Datasetsourcetype enum")
	}

	return nil
}

func (e Datasetsourcetype) String() string {
	return string(e)
}
