//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type Datasetstatus string

const (
	Datasetstatus_Validating Datasetstatus = "validating"
	Datasetstatus_Pending    Datasetstatus = "pending"
	Datasetstatus_Copying    Datasetstatus = "copying"
	Datasetstatus_Ready      Datasetstatus = "ready"
	Datasetstatus_Failed     Datasetstatus = "failed"
)

var DatasetstatusAllValues = []Datasetstatus{
	Datasetstatus_Validating,
	Datasetstatus_Pending,
	Datasetstatus_Copying,
	Datasetstatus_Ready,
	Datasetstatus_Failed,
}

func (e *Datasetstatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "validating":
		*e = Datasetstatus_Validating
	case "pending":
		*e = Datasetstatus_Pending
	case "copying":
		*e = Datasetstatus_Copying
	case "ready":
		*e = Datasetstatus_Ready
	case "failed":
		*e = Datasetstatus_Failed
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for Datasetstatus enum")
	}

	return nil
}

func (e Datasetstatus) String() string {
	return string(e)
}
