//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type FinetunedModels struct {
	ID            uuid.UUID `sql:"primary_key"`
	Name          string
	SourceType    Sourcetype
	SourceDetails string
	CreatedAt     time.Time
	DataConfig    *string
	BaseFm        *Basefm
}
