//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type Inferencestatus string

const (
	Inferencestatus_Queued        Inferencestatus = "queued"
	Inferencestatus_Download      Inferencestatus = "download"
	Inferencestatus_PreInference  Inferencestatus = "pre_inference"
	Inferencestatus_Inference     Inferencestatus = "inference"
	Inferencestatus_PostInference Inferencestatus = "post_inference"
	Inferencestatus_Complete      Inferencestatus = "complete"
	Inferencestatus_Failed        Inferencestatus = "failed"
)

var InferencestatusAllValues = []Inferencestatus{
	Inferencestatus_Queued,
	Inferencestatus_Download,
	Inferencestatus_PreInference,
	Inferencestatus_Inference,
	Inferencestatus_PostInference,
	Inferencestatus_Complete,
	Inferencestatus_Failed,
}

func (e *Inferencestatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "queued":
		*e = Inferencestatus_Queued
	case "download":
		*e = Inferencestatus_Download
	case "pre_inference":
		*e = Inferencestatus_PreInference
	case "inference":
		*e = Inferencestatus_Inference
	case "post_inference":
		*e = Inferencestatus_PostInference
	case "complete":
		*e = Inferencestatus_Complete
	case "failed":
		*e = Inferencestatus_Failed
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for Inferencestatus enum")
	}

	return nil
}

func (e Inferencestatus) String() string {
	return string(e)
}
