//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Inferences struct {
	ID           uuid.UUID `sql:"primary_key"`
	Name         string
	Query        *string
	CreatedAt    time.Time
	Results      *string
	UserEmail    string
	Status       Inferencestatus
	UpdatedAt    time.Time
	ErrorStage   *string
	ErrorMessage *string
}
