//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Jobs struct {
	ID             uuid.UUID `sql:"primary_key"`
	JobName        string
	DatasetID      uuid.UUID
	BatchSize      int32
	NumClasses     int32
	Backbone       string
	NumEpochs      int32
	TaskType       Tasktype
	Status         Jobstatus
	CreatedAt      time.Time
	StartedAt      *time.Time
	CompletedAt    *time.Time
	SagemakerJobID *string
	ErrorMessage   *string
	IsDeleted      bool
	DeletedAt      *time.Time
	FailedAt       *time.Time
	NumWorkers     *int32
	DataPath       *string
	Usecase        *string
	Means          *string
	Stds           *string
	NumFrames      *int32
	OutputBands    *int32
	Indices        *string
	DatasetBands   *string
	LossFunction   *string
	ImgGrep        *string
	LabelGrep      *string
	TrainSplitPath *string
	ValSplitPath   *string
	TestSplitPath  *string
}
