//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type Jobstatus string

const (
	Jobstatus_Pending   Jobstatus = "pending"
	Jobstatus_Running   Jobstatus = "running"
	Jobstatus_Completed Jobstatus = "completed"
	Jobstatus_Failed    Jobstatus = "failed"
	Jobstatus_Deleted   Jobstatus = "deleted"
)

var JobstatusAllValues = []Jobstatus{
	Jobstatus_Pending,
	Jobstatus_Running,
	Jobstatus_Completed,
	Jobstatus_Failed,
	Jobstatus_Deleted,
}

func (e *Jobstatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "pending":
		*e = Jobstatus_Pending
	case "running":
		*e = Jobstatus_Running
	case "completed":
		*e = Jobstatus_Completed
	case "failed":
		*e = Jobstatus_Failed
	case "deleted":
		*e = Jobstatus_Deleted
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for Jobstatus enum")
	}

	return nil
}

func (e Jobstatus) String() string {
	return string(e)
}
