//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type PreloadedEvents struct {
	ID           uuid.UUID `sql:"primary_key" json:"id"`
	EventName    string `json:"event_name"`
	EventDetails *string `json:"event_details"`
	CreatedAt    time.Time `json:"created_at"`
	InferenceID  *uuid.UUID `json:"inference_id"`
}
