//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type Sourcetype string

const (
	Sourcetype_Huggingface Sourcetype = "huggingface"
	Sourcetype_S3          Sourcetype = "s3"
)

var SourcetypeAllValues = []Sourcetype{
	Sourcetype_Huggingface,
	Sourcetype_S3,
}

func (e *Sourcetype) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "huggingface":
		*e = Sourcetype_Huggingface
	case "s3":
		*e = Sourcetype_S3
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for Sourcetype enum")
	}

	return nil
}

func (e Sourcetype) String() string {
	return string(e)
}
