//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type Tasktype string

const (
	Tasktype_Classification Tasktype = "classification"
	Tasktype_Segmentation   Tasktype = "segmentation"
)

var TasktypeAllValues = []Tasktype{
	Tasktype_Classification,
	Tasktype_Segmentation,
}

func (e *Tasktype) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "classification":
		*e = Tasktype_Classification
	case "segmentation":
		*e = Tasktype_Segmentation
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for Tasktype enum")
	}

	return nil
}

func (e Tasktype) String() string {
	return string(e)
}
