//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AlembicVersion = newAlembicVersionTable("public", "alembic_version", "")

type alembicVersionTable struct {
	postgres.Table

	// Columns
	VersionNum postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AlembicVersionTable struct {
	alembicVersionTable

	EXCLUDED alembicVersionTable
}

// AS creates new AlembicVersionTable with assigned alias
func (a AlembicVersionTable) AS(alias string) *AlembicVersionTable {
	return newAlembicVersionTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AlembicVersionTable with assigned schema name
func (a AlembicVersionTable) FromSchema(schemaName string) *AlembicVersionTable {
	return newAlembicVersionTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AlembicVersionTable with assigned table prefix
func (a AlembicVersionTable) WithPrefix(prefix string) *AlembicVersionTable {
	return newAlembicVersionTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AlembicVersionTable with assigned table suffix
func (a AlembicVersionTable) WithSuffix(suffix string) *AlembicVersionTable {
	return newAlembicVersionTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAlembicVersionTable(schemaName, tableName, alias string) *AlembicVersionTable {
	return &AlembicVersionTable{
		alembicVersionTable: newAlembicVersionTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newAlembicVersionTableImpl("", "excluded", ""),
	}
}

func newAlembicVersionTableImpl(schemaName, tableName, alias string) alembicVersionTable {
	var (
		VersionNumColumn = postgres.StringColumn("version_num")
		allColumns       = postgres.ColumnList{VersionNumColumn}
		mutableColumns   = postgres.ColumnList{}
		defaultColumns   = postgres.ColumnList{}
	)

	return alembicVersionTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		VersionNum: VersionNumColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
