//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Artifacts = newArtifactsTable("public", "artifacts", "")

type artifactsTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	JobID        postgres.ColumnString
	ArtifactType postgres.ColumnString
	ArtifactPath postgres.ColumnString
	CreatedAt    postgres.ColumnTimestamp
	IsDeleted    postgres.ColumnBool
	DeletedAt    postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ArtifactsTable struct {
	artifactsTable

	EXCLUDED artifactsTable
}

// AS creates new ArtifactsTable with assigned alias
func (a ArtifactsTable) AS(alias string) *ArtifactsTable {
	return newArtifactsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ArtifactsTable with assigned schema name
func (a ArtifactsTable) FromSchema(schemaName string) *ArtifactsTable {
	return newArtifactsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ArtifactsTable with assigned table prefix
func (a ArtifactsTable) WithPrefix(prefix string) *ArtifactsTable {
	return newArtifactsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ArtifactsTable with assigned table suffix
func (a ArtifactsTable) WithSuffix(suffix string) *ArtifactsTable {
	return newArtifactsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newArtifactsTable(schemaName, tableName, alias string) *ArtifactsTable {
	return &ArtifactsTable{
		artifactsTable: newArtifactsTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newArtifactsTableImpl("", "excluded", ""),
	}
}

func newArtifactsTableImpl(schemaName, tableName, alias string) artifactsTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		JobIDColumn        = postgres.StringColumn("job_id")
		ArtifactTypeColumn = postgres.StringColumn("artifact_type")
		ArtifactPathColumn = postgres.StringColumn("artifact_path")
		CreatedAtColumn    = postgres.TimestampColumn("created_at")
		IsDeletedColumn    = postgres.BoolColumn("is_deleted")
		DeletedAtColumn    = postgres.TimestampColumn("deleted_at")
		allColumns         = postgres.ColumnList{IDColumn, JobIDColumn, ArtifactTypeColumn, ArtifactPathColumn, CreatedAtColumn, IsDeletedColumn, DeletedAtColumn}
		mutableColumns     = postgres.ColumnList{JobIDColumn, ArtifactTypeColumn, ArtifactPathColumn, CreatedAtColumn, IsDeletedColumn, DeletedAtColumn}
		defaultColumns     = postgres.ColumnList{}
	)

	return artifactsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		JobID:        JobIDColumn,
		ArtifactType: ArtifactTypeColumn,
		ArtifactPath: ArtifactPathColumn,
		CreatedAt:    CreatedAtColumn,
		IsDeleted:    IsDeletedColumn,
		DeletedAt:    DeletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
