//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var FinetunedModels = newFinetunedModelsTable("public", "finetuned_models", "")

type finetunedModelsTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	Name          postgres.ColumnString
	SourceType    postgres.ColumnString
	SourceDetails postgres.ColumnString
	CreatedAt     postgres.ColumnTimestamp
	DataConfig    postgres.ColumnString
	BaseFm        postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type FinetunedModelsTable struct {
	finetunedModelsTable

	EXCLUDED finetunedModelsTable
}

// AS creates new FinetunedModelsTable with assigned alias
func (a FinetunedModelsTable) AS(alias string) *FinetunedModelsTable {
	return newFinetunedModelsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FinetunedModelsTable with assigned schema name
func (a FinetunedModelsTable) FromSchema(schemaName string) *FinetunedModelsTable {
	return newFinetunedModelsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FinetunedModelsTable with assigned table prefix
func (a FinetunedModelsTable) WithPrefix(prefix string) *FinetunedModelsTable {
	return newFinetunedModelsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FinetunedModelsTable with assigned table suffix
func (a FinetunedModelsTable) WithSuffix(suffix string) *FinetunedModelsTable {
	return newFinetunedModelsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFinetunedModelsTable(schemaName, tableName, alias string) *FinetunedModelsTable {
	return &FinetunedModelsTable{
		finetunedModelsTable: newFinetunedModelsTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newFinetunedModelsTableImpl("", "excluded", ""),
	}
}

func newFinetunedModelsTableImpl(schemaName, tableName, alias string) finetunedModelsTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		NameColumn          = postgres.StringColumn("name")
		SourceTypeColumn    = postgres.StringColumn("source_type")
		SourceDetailsColumn = postgres.StringColumn("source_details")
		CreatedAtColumn     = postgres.TimestampColumn("created_at")
		DataConfigColumn    = postgres.StringColumn("data_config")
		BaseFmColumn        = postgres.StringColumn("base_fm")
		allColumns          = postgres.ColumnList{IDColumn, NameColumn, SourceTypeColumn, SourceDetailsColumn, CreatedAtColumn, DataConfigColumn, BaseFmColumn}
		mutableColumns      = postgres.ColumnList{NameColumn, SourceTypeColumn, SourceDetailsColumn, CreatedAtColumn, DataConfigColumn, BaseFmColumn}
		defaultColumns      = postgres.ColumnList{}
	)

	return finetunedModelsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		Name:          NameColumn,
		SourceType:    SourceTypeColumn,
		SourceDetails: SourceDetailsColumn,
		CreatedAt:     CreatedAtColumn,
		DataConfig:    DataConfigColumn,
		BaseFm:        BaseFmColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
