//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Inferences = newInferencesTable("public", "inferences", "")

type inferencesTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	Name         postgres.ColumnString
	Query        postgres.ColumnString
	CreatedAt    postgres.ColumnTimestamp
	Results      postgres.ColumnString
	UserEmail    postgres.ColumnString
	Status       postgres.ColumnString
	UpdatedAt    postgres.ColumnTimestamp
	ErrorStage   postgres.ColumnString
	ErrorMessage postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type InferencesTable struct {
	inferencesTable

	EXCLUDED inferencesTable
}

// AS creates new InferencesTable with assigned alias
func (a InferencesTable) AS(alias string) *InferencesTable {
	return newInferencesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new InferencesTable with assigned schema name
func (a InferencesTable) FromSchema(schemaName string) *InferencesTable {
	return newInferencesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new InferencesTable with assigned table prefix
func (a InferencesTable) WithPrefix(prefix string) *InferencesTable {
	return newInferencesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new InferencesTable with assigned table suffix
func (a InferencesTable) WithSuffix(suffix string) *InferencesTable {
	return newInferencesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newInferencesTable(schemaName, tableName, alias string) *InferencesTable {
	return &InferencesTable{
		inferencesTable: newInferencesTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newInferencesTableImpl("", "excluded", ""),
	}
}

func newInferencesTableImpl(schemaName, tableName, alias string) inferencesTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		NameColumn         = postgres.StringColumn("name")
		QueryColumn        = postgres.StringColumn("query")
		CreatedAtColumn    = postgres.TimestampColumn("created_at")
		ResultsColumn      = postgres.StringColumn("results")
		UserEmailColumn    = postgres.StringColumn("user_email")
		StatusColumn       = postgres.StringColumn("status")
		UpdatedAtColumn    = postgres.TimestampColumn("updated_at")
		ErrorStageColumn   = postgres.StringColumn("error_stage")
		ErrorMessageColumn = postgres.StringColumn("error_message")
		allColumns         = postgres.ColumnList{IDColumn, NameColumn, QueryColumn, CreatedAtColumn, ResultsColumn, UserEmailColumn, StatusColumn, UpdatedAtColumn, ErrorStageColumn, ErrorMessageColumn}
		mutableColumns     = postgres.ColumnList{NameColumn, QueryColumn, CreatedAtColumn, ResultsColumn, UserEmailColumn, StatusColumn, UpdatedAtColumn, ErrorStageColumn, ErrorMessageColumn}
		defaultColumns     = postgres.ColumnList{}
	)

	return inferencesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		Name:         NameColumn,
		Query:        QueryColumn,
		CreatedAt:    CreatedAtColumn,
		Results:      ResultsColumn,
		UserEmail:    UserEmailColumn,
		Status:       StatusColumn,
		UpdatedAt:    UpdatedAtColumn,
		ErrorStage:   ErrorStageColumn,
		ErrorMessage: ErrorMessageColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
