//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var InferenceFinetunedModel = newInferenceFinetunedModelTable("public", "inference_finetuned_model", "")

type inferenceFinetunedModelTable struct {
	postgres.Table

	// Columns
	InferenceID      postgres.ColumnString
	FinetunedModelID postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type InferenceFinetunedModelTable struct {
	inferenceFinetunedModelTable

	EXCLUDED inferenceFinetunedModelTable
}

// AS creates new InferenceFinetunedModelTable with assigned alias
func (a InferenceFinetunedModelTable) AS(alias string) *InferenceFinetunedModelTable {
	return newInferenceFinetunedModelTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new InferenceFinetunedModelTable with assigned schema name
func (a InferenceFinetunedModelTable) FromSchema(schemaName string) *InferenceFinetunedModelTable {
	return newInferenceFinetunedModelTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new InferenceFinetunedModelTable with assigned table prefix
func (a InferenceFinetunedModelTable) WithPrefix(prefix string) *InferenceFinetunedModelTable {
	return newInferenceFinetunedModelTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new InferenceFinetunedModelTable with assigned table suffix
func (a InferenceFinetunedModelTable) WithSuffix(suffix string) *InferenceFinetunedModelTable {
	return newInferenceFinetunedModelTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newInferenceFinetunedModelTable(schemaName, tableName, alias string) *InferenceFinetunedModelTable {
	return &InferenceFinetunedModelTable{
		inferenceFinetunedModelTable: newInferenceFinetunedModelTableImpl(schemaName, tableName, alias),
		EXCLUDED:                     newInferenceFinetunedModelTableImpl("", "excluded", ""),
	}
}

func newInferenceFinetunedModelTableImpl(schemaName, tableName, alias string) inferenceFinetunedModelTable {
	var (
		InferenceIDColumn      = postgres.StringColumn("inference_id")
		FinetunedModelIDColumn = postgres.StringColumn("finetuned_model_id")
		allColumns             = postgres.ColumnList{InferenceIDColumn, FinetunedModelIDColumn}
		mutableColumns         = postgres.ColumnList{}
		defaultColumns         = postgres.ColumnList{}
	)

	return inferenceFinetunedModelTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		InferenceID:      InferenceIDColumn,
		FinetunedModelID: FinetunedModelIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
