//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Jobs = newJobsTable("public", "jobs", "")

type jobsTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnString
	JobName        postgres.ColumnString
	DatasetID      postgres.ColumnString
	BatchSize      postgres.ColumnInteger
	NumClasses     postgres.ColumnInteger
	Backbone       postgres.ColumnString
	NumEpochs      postgres.ColumnInteger
	TaskType       postgres.ColumnString
	Status         postgres.ColumnString
	CreatedAt      postgres.ColumnTimestamp
	StartedAt      postgres.ColumnTimestamp
	CompletedAt    postgres.ColumnTimestamp
	SagemakerJobID postgres.ColumnString
	ErrorMessage   postgres.ColumnString
	IsDeleted      postgres.ColumnBool
	DeletedAt      postgres.ColumnTimestamp
	FailedAt       postgres.ColumnTimestamp
	NumWorkers     postgres.ColumnInteger
	DataPath       postgres.ColumnString
	Usecase        postgres.ColumnString
	Means          postgres.ColumnString
	Stds           postgres.ColumnString
	NumFrames      postgres.ColumnInteger
	OutputBands    postgres.ColumnInteger
	Indices        postgres.ColumnString
	DatasetBands   postgres.ColumnString
	LossFunction   postgres.ColumnString
	ImgGrep        postgres.ColumnString
	LabelGrep      postgres.ColumnString
	TrainSplitPath postgres.ColumnString
	ValSplitPath   postgres.ColumnString
	TestSplitPath  postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type JobsTable struct {
	jobsTable

	EXCLUDED jobsTable
}

// AS creates new JobsTable with assigned alias
func (a JobsTable) AS(alias string) *JobsTable {
	return newJobsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new JobsTable with assigned schema name
func (a JobsTable) FromSchema(schemaName string) *JobsTable {
	return newJobsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new JobsTable with assigned table prefix
func (a JobsTable) WithPrefix(prefix string) *JobsTable {
	return newJobsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new JobsTable with assigned table suffix
func (a JobsTable) WithSuffix(suffix string) *JobsTable {
	return newJobsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newJobsTable(schemaName, tableName, alias string) *JobsTable {
	return &JobsTable{
		jobsTable: newJobsTableImpl(schemaName, tableName, alias),
		EXCLUDED:  newJobsTableImpl("", "excluded", ""),
	}
}

func newJobsTableImpl(schemaName, tableName, alias string) jobsTable {
	var (
		IDColumn             = postgres.StringColumn("id")
		JobNameColumn        = postgres.StringColumn("job_name")
		DatasetIDColumn      = postgres.StringColumn("dataset_id")
		BatchSizeColumn      = postgres.IntegerColumn("batch_size")
		NumClassesColumn     = postgres.IntegerColumn("num_classes")
		BackboneColumn       = postgres.StringColumn("backbone")
		NumEpochsColumn      = postgres.IntegerColumn("num_epochs")
		TaskTypeColumn       = postgres.StringColumn("task_type")
		StatusColumn         = postgres.StringColumn("status")
		CreatedAtColumn      = postgres.TimestampColumn("created_at")
		StartedAtColumn      = postgres.TimestampColumn("started_at")
		CompletedAtColumn    = postgres.TimestampColumn("completed_at")
		SagemakerJobIDColumn = postgres.StringColumn("sagemaker_job_id")
		ErrorMessageColumn   = postgres.StringColumn("error_message")
		IsDeletedColumn      = postgres.BoolColumn("is_deleted")
		DeletedAtColumn      = postgres.TimestampColumn("deleted_at")
		FailedAtColumn       = postgres.TimestampColumn("failed_at")
		NumWorkersColumn     = postgres.IntegerColumn("num_workers")
		DataPathColumn       = postgres.StringColumn("data_path")
		UsecaseColumn        = postgres.StringColumn("usecase")
		MeansColumn          = postgres.StringColumn("means")
		StdsColumn           = postgres.StringColumn("stds")
		NumFramesColumn      = postgres.IntegerColumn("num_frames")
		OutputBandsColumn    = postgres.IntegerColumn("output_bands")
		IndicesColumn        = postgres.StringColumn("indices")
		DatasetBandsColumn   = postgres.StringColumn("dataset_bands")
		LossFunctionColumn   = postgres.StringColumn("loss_function")
		ImgGrepColumn        = postgres.StringColumn("img_grep")
		LabelGrepColumn      = postgres.StringColumn("label_grep")
		TrainSplitPathColumn = postgres.StringColumn("train_split_path")
		ValSplitPathColumn   = postgres.StringColumn("val_split_path")
		TestSplitPathColumn  = postgres.StringColumn("test_split_path")
		allColumns           = postgres.ColumnList{IDColumn, JobNameColumn, DatasetIDColumn, BatchSizeColumn, NumClassesColumn, BackboneColumn, NumEpochsColumn, TaskTypeColumn, StatusColumn, CreatedAtColumn, StartedAtColumn, CompletedAtColumn, SagemakerJobIDColumn, ErrorMessageColumn, IsDeletedColumn, DeletedAtColumn, FailedAtColumn, NumWorkersColumn, DataPathColumn, UsecaseColumn, MeansColumn, StdsColumn, NumFramesColumn, OutputBandsColumn, IndicesColumn, DatasetBandsColumn, LossFunctionColumn, ImgGrepColumn, LabelGrepColumn, TrainSplitPathColumn, ValSplitPathColumn, TestSplitPathColumn}
		mutableColumns       = postgres.ColumnList{JobNameColumn, DatasetIDColumn, BatchSizeColumn, NumClassesColumn, BackboneColumn, NumEpochsColumn, TaskTypeColumn, StatusColumn, CreatedAtColumn, StartedAtColumn, CompletedAtColumn, SagemakerJobIDColumn, ErrorMessageColumn, IsDeletedColumn, DeletedAtColumn, FailedAtColumn, NumWorkersColumn, DataPathColumn, UsecaseColumn, MeansColumn, StdsColumn, NumFramesColumn, OutputBandsColumn, IndicesColumn, DatasetBandsColumn, LossFunctionColumn, ImgGrepColumn, LabelGrepColumn, TrainSplitPathColumn, ValSplitPathColumn, TestSplitPathColumn}
		defaultColumns       = postgres.ColumnList{}
	)

	return jobsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		JobName:        JobNameColumn,
		DatasetID:      DatasetIDColumn,
		BatchSize:      BatchSizeColumn,
		NumClasses:     NumClassesColumn,
		Backbone:       BackboneColumn,
		NumEpochs:      NumEpochsColumn,
		TaskType:       TaskTypeColumn,
		Status:         StatusColumn,
		CreatedAt:      CreatedAtColumn,
		StartedAt:      StartedAtColumn,
		CompletedAt:    CompletedAtColumn,
		SagemakerJobID: SagemakerJobIDColumn,
		ErrorMessage:   ErrorMessageColumn,
		IsDeleted:      IsDeletedColumn,
		DeletedAt:      DeletedAtColumn,
		FailedAt:       FailedAtColumn,
		NumWorkers:     NumWorkersColumn,
		DataPath:       DataPathColumn,
		Usecase:        UsecaseColumn,
		Means:          MeansColumn,
		Stds:           StdsColumn,
		NumFrames:      NumFramesColumn,
		OutputBands:    OutputBandsColumn,
		Indices:        IndicesColumn,
		DatasetBands:   DatasetBandsColumn,
		LossFunction:   LossFunctionColumn,
		ImgGrep:        ImgGrepColumn,
		LabelGrep:      LabelGrepColumn,
		TrainSplitPath: TrainSplitPathColumn,
		ValSplitPath:   ValSplitPathColumn,
		TestSplitPath:  TestSplitPathColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
