//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PreloadedEvents = newPreloadedEventsTable("public", "preloaded_events", "")

type preloadedEventsTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	EventName    postgres.ColumnString
	EventDetails postgres.ColumnString
	CreatedAt    postgres.ColumnTimestamp
	InferenceID  postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PreloadedEventsTable struct {
	preloadedEventsTable

	EXCLUDED preloadedEventsTable
}

// AS creates new PreloadedEventsTable with assigned alias
func (a PreloadedEventsTable) AS(alias string) *PreloadedEventsTable {
	return newPreloadedEventsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PreloadedEventsTable with assigned schema name
func (a PreloadedEventsTable) FromSchema(schemaName string) *PreloadedEventsTable {
	return newPreloadedEventsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PreloadedEventsTable with assigned table prefix
func (a PreloadedEventsTable) WithPrefix(prefix string) *PreloadedEventsTable {
	return newPreloadedEventsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PreloadedEventsTable with assigned table suffix
func (a PreloadedEventsTable) WithSuffix(suffix string) *PreloadedEventsTable {
	return newPreloadedEventsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPreloadedEventsTable(schemaName, tableName, alias string) *PreloadedEventsTable {
	return &PreloadedEventsTable{
		preloadedEventsTable: newPreloadedEventsTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newPreloadedEventsTableImpl("", "excluded", ""),
	}
}

func newPreloadedEventsTableImpl(schemaName, tableName, alias string) preloadedEventsTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		EventNameColumn    = postgres.StringColumn("event_name")
		EventDetailsColumn = postgres.StringColumn("event_details")
		CreatedAtColumn    = postgres.TimestampColumn("created_at")
		InferenceIDColumn  = postgres.StringColumn("inference_id")
		allColumns         = postgres.ColumnList{IDColumn, EventNameColumn, EventDetailsColumn, CreatedAtColumn, InferenceIDColumn}
		mutableColumns     = postgres.ColumnList{EventNameColumn, EventDetailsColumn, CreatedAtColumn, InferenceIDColumn}
		defaultColumns     = postgres.ColumnList{}
	)

	return preloadedEventsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		EventName:    EventNameColumn,
		EventDetails: EventDetailsColumn,
		CreatedAt:    CreatedAtColumn,
		InferenceID:  InferenceIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
