apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-app
  labels:
    app: prediction-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prediction-app
  template:
    metadata:
      labels:
        app: prediction-app
    spec:
      imagePullSecrets:
        - name: ecr-registry-key
      containers:
        - name: prediction-container
          image: 244822573120.dkr.ecr.us-west-2.amazonaws.com/prediction:mvp
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: cache-volume
              mountPath: /root/.cache
          env:
          - name: BUCKET_NAME
            value: "r2o-models"
          - name: USECASE
            value: "burn_scars"
          - name: API_KEY_VALIDATION_URL
            value: "https://dev.fm.dsig.net/api/validate"
          - name: DOWNLOAD_FOLDER
            value: "/root/.cache/data/"
          envFrom:
            - configMapRef:
                name: oidc-envs
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: prediction-cache-pvc
