apiVersion: v1
kind: Service
metadata:
  name: prediction-service
spec:
  selector:
    app: prediction-app
  ports:
  - port: 443
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: floods-service
spec:
  selector:
    app: flood-app
  type: ClusterIP
